# Generated by Django 4.2.3 on 2023-08-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
