# Generated by Django 4.2.3 on 2023-09-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_certificate_certifying_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(to="projects.profile"),
        ),
    ]
